
set guifont=Monaco\ 16

set history=2000

filetype on 

filetype indent on

filetype plugin on

filetype plugin indent on

set autoread

set mouse=a

set ruler

set showcmd

set showmode

set number

" set nowrap

set tabstop=4

set shiftwidth=4

set et

" set cursorline
set encoding=utf-8
set relativenumber
syntax on
set autoindent
set backspace=2
set ts=4 
set expandtab
set hlsearch
au BufReadPost * if line("'\"") > 0|if line("'\"") <= line("$")|exe("norm '\"")|else|exe "norm $"|endif|endif
set ts=4
set expandtab
set autoindent


" commentary
" 为python和shell等添加注释
autocmd FileType python,shell,coffee set commentstring=#\ %s
" 修改注释风格
autocmd FileType java,c,cpp set commentstring=//\ %s

